# NumPy Basics Practice
Run one cell at a time while practicing.

In [9]:
# Import NumPy for fast numerical array operations
import numpy as np

In [10]:
# SECTION 1: Creating Arrays
# Create first NumPy array with small integers
a = np.array([1, 2, 3, 4, 5])

# Create second NumPy array for pairwise operations
b = np.array([10, 20, 30, 40, 50])

# Print the actual values of array a
print('a:', a)

# Print the actual values of array b
print('b:', b)

# Print datatype of elements stored in array a
print('dtype:', a.dtype)

# Print shape of array a (rows, columns); here it is 1D with 5 items
print('shape:', a.shape)

# Create and print an array of zeros of length 5
print('zeros(5):', np.zeros(5))

# Create and print an array of ones of length 5
print('ones(5):', np.ones(5))

# Create values from 0 to 10 (exclusive) with step size 2
print('arange:', np.arange(0, 10, 2))

# Create 5 equally spaced values between 0 and 1 (inclusive)
print('linspace:', np.linspace(0, 1, 5))

a: [1 2 3 4 5]
b: [10 20 30 40 50]
dtype: int64
shape: (5,)
zeros(5): [0. 0. 0. 0. 0.]
ones(5): [1. 1. 1. 1. 1.]
arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [ ]:
# SECTION 2: Vectorized Math
# Add corresponding elements of a and b
print('a + b:', a + b)

# Subtract corresponding elements of b from a
print('a - b:', a - b)

# Multiply corresponding elements of a and b
print('a * b:', a * b)

# Divide corresponding elements of a by b
print('a / b:', a / b)

# Square each element in a
print('a ** 2:', a ** 2)

# Take square root of each element in a and round for readability
print('sqrt(a):', np.sqrt(a).round(3))

a + b: [11 22 33 44 55]
a - b: [ -9 -18 -27 -36 -45]
a * b: [ 10  40  90 160 250]
a / b: [0.1 0.1 0.1 0.1 0.1]
a ** 2: [ 1  4  9 16 25]
sqrt(a): [1.    1.414 1.732 2.    2.236]


In [ ]:
# SECTION 3: Aggregations
# Create sample array that represents house sizes
data = np.array([600, 800, 1000, 1200, 1500])

# Compute arithmetic mean of all values
print('Mean:', np.mean(data))

# Compute middle value after sorting
print('Median:', np.median(data))

# Compute standard deviation (spread of values)
print('Std Dev:', np.std(data).round(2))

# Compute variance (square of standard deviation)
print('Variance:', np.var(data))

# Print minimum and maximum values in the array
print('Min / Max:', np.min(data), '/', np.max(data))

# Print index of minimum and index of maximum values
print('argmin / argmax:', np.argmin(data), np.argmax(data))

Mean: 1020.0
Median: 1000.0
Std Dev: 312.41
Variance: 97600.0
Min / Max: 600 / 1500
argmin / argmax: 0 4


In [ ]:
# SECTION 4: Dot Product & Matrix Ops
# Define model weights for three features
weights = np.array([0.5, 0.3, 0.2])

# Define one sample input vector with three feature values
features = np.array([1.0, 2.0, 3.0])

# Compute dot product (weighted sum) used in linear models
print('w dot x =', np.dot(weights, features))

# Define first 2x2 matrix
W = np.array([[1, 2], [3, 4]])

# Define second 2x2 matrix
X = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
print('W @ X =\n', W @ X)

# Create and print 3x3 identity matrix
print('I3 =\n', np.eye(3))

w dot x = 1.7000000000000002
W @ X =
 [[19 22]
 [43 50]]
I3 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# SECTION 5: Normalization
# Create raw feature array as float for scaling operations
raw = np.array([600, 800, 1000, 1200, 1500], dtype=float)

# Apply Min-Max scaling to map values into range [0, 1]
min_max = (raw - raw.min()) / (raw.max() - raw.min())

# Apply Z-score scaling to center data around 0 with unit standard deviation
z_score = (raw - raw.mean()) / raw.std()

# Print Min-Max scaled values
print('Min-Max:', min_max.round(3))

# Print Z-score scaled values
print('Z-score:', z_score.round(3))

Min-Max: [0.    0.222 0.444 0.667 1.   ]
Z-score: [-1.344 -0.704 -0.064  0.576  1.536]
